version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mitienda
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mitienda_local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api-network

  postgres-test:
    image: postgres:15
    restart: always
    container_name: postgres-test
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=mitienda_test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mitienda_local_test
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  web-root:
    driver: local
  postgres-data:
    driver: local
